# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95b29393bb60fa14966425f863bd9520d60fb2b75bbce84596c9a9b3ad4afbce99228937385f7d9674a6c6c55d954de7967d8639c6840a35d4a103ba6510d7c

test:
  secret_key_base: 099346f68b01046343782d373c4db3da3196e89f23f7cb334da828227b01ac9862cb5d3cff6fa88cbcfbc71cb1dac89ac9d9b93fbfc24dd848139d6b30b46911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
